### ISSUE TITLE
Subscription permanently closed

### ISSUE THREAD

**Issue by Northo** [hersle/light#1]
The subscription feature is non-reachable due to a logics error at[ lines 135 and 136 in `light.py`](https://github.com/hersle/light/blob/169c2cf1f05464cb5c339f6c48eef85d04d66d7b/light.py#L135-L136). This causes any POST request to `subscribe.php` to return
> Epostregistrering stengt.

### Proposed solution:
Remove line 135 and 136.

### Git blame:
@hersle 1b9833225ae50483a8e5a9bd03accb5f4d3c6756

**Comment by hersle** [comment]
Thank you for making us aware of this issue.

Removal of the mentioned lines is a too naive solution to this issue. This is due to the incompleteness of the email subscription system. Further enhancements to the subscription system is required before the mentioned lines can be removed.

This is an extensive process. This issue is of utmost importance, however, and I assure you our engineers are working day and night to fix this issue.

**Comment by Northo** [comment]
I am bumping this, as it is a very coveted feature.

**Comment by Northo** [comment]
Bump

**Comment by hersle** [comment]
Hi Northo.

Thank you for reminding us of this severe issue. We apologize for any inconvenience that it may cause you and hope to have it resolved in the near future.

Sincerely, the lysloggteam.

**Comment by Northo** [comment]
Do you believe that the near future might be the present in the near future? This is in fact the source of a non-trivial amount of inconvenience.

**Comment by hersle** [comment]
Hello Northo,

We are pleased to announce that our development team is currently finalizing the process of thinking about how to resolve the problem. The team will shortly begin the process of consideration of the initialization of the development process.

Thank you once again for the reminder.

**Comment by hersle** [comment]
Dear Northo,

The team and I is proud to announce that we have finally repoened the subscription system, after a period of immense work. The subscription system was opened using your proposed solution, as you can see in #272ce69. 

Again, we sincerely apologize for any inconveniences that this downtime may have caused. Should there be any other issues with the subscription system, we would greatly appreciate you voicing your concerns to us again.

Thank you for your continued attention in this matter.

**Comment by Northo** [comment]
Great! Nice work, thank you!
